[package]
name = "hello"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concurrent-hash-map="0.0.6"
futures = "0.3.17"
tokio = "1.13.0"
