[package]
name = "fltk_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.1"
fltk-flex = "0.1"
fltk-theme = "0.1"
